### PR TITLE
add universal receptor data DataArray interface

### PR DESCRIPTION
**Pull request by armaan-abraham**
* remove the option to pass the luminex receptor data as np.ndarray in optimizeLoss and helper functions, instead enforcing xarray.DataArray
* jax.jit only allows primitive python types and np arrays, so this posed a problem for the DataArray interface. Pass receptor data as a static argument to jit. jit static arguments must be hashable, so create hashable subclass of xarray.DataArray, HDataArray. HDataArray should now be the universal type of the receptor data.
* remove autoscale metrics as their performance was comparable / worse than MSE with scaling factors

### CODE REVIEW

**Comment by cyrillustan** [comment]
I think you got the opposite idea? For the part of code that will be run repeatedly by the optimization algorithm, we should try to minimize the unhelpful and slow indexing/labeling work and just use numpy array instead of xarray.

**Comment by armaan-abraham** [comment]
@cyrillustan I believe that this is what Dr. Meyer had in mind, i.e. "The data stays as an xarray. However, in the objective function, you only ever touch the data at the very end, when you take the difference."

I also believe that this approach is better, the performance hit is negligible and having `data` be an xarray makes a lot of the operations cleaner.

**Comment by aarmey** [comment]
I would suggest profiling the code. Unless it's spending all its time with some xarray operation, there is no need to worry about its performance.

**Comment by armaan-abraham** [comment]
Update: still running tests to see if the hackiness of this solution is worth it

**Comment by armaan-abraham** [comment]
Outdated now. Closing.

**Pull request closed without merging**
